### ISSUE TITLE
touchpad feels sluggish and weird

### ISSUE THREAD

**Issue by iljo-dp** [MultimediaLucario/Lenovo-ThinkPad-T480#22]
When using the thinkpad touch pad the movement feels very sluggish and skips kind of all over the place when moving with it. When using an external mouse it all feels great and smooth, but when using a touch pad it all kind of lags and skips around.
This issue isn't appear ant when using Linux or windows

**Comment by iljo-dp** [comment]
also touch pad gestures don't work, swiping or taping all don't work.

**Comment by MultimediaLucario** [comment]
What are the specs of your T480?

**Comment by coderang-gk** [comment]
Exact same problem, now i cant even downgrade mac OS, stuck w laggy trackpad

**Comment by kadalcj** [comment]
I had the same experience when using your config. But I had different story when using the valnoxy config, the touch pad work better there. I've tried to change and combine your config with that, but nothing happen.

I like your config bro but, it would be really nice if you could try it and do some changes to your configs.
I had the same specs as yours btw, just the wifi doesn't work because the port gone bad. Thanks.
